### ISSUE TITLE
Malformed tables in https://project-awesome.org/Dvergar/awesome-haxe-gamedev#game-engines

### ISSUE THREAD

**Issue by Inc0n** [Dvergar/awesome-haxe-gamedev#11]
Hi,

The tables in https://project-awesome.org/Dvergar/awesome-haxe-gamedev, are all malformed. 
It looks to me to be org-mode text table, perhaps you want to fix that.

<img width="960" alt="Screenshot 2021-09-11 at 16 44 48" src="https://user-images.githubusercontent.com/33980911/132953510-5a6311e4-cc2a-4e97-b0c0-a718c8e47ea6.png">

**Comment by AdamHarte** [comment]
Renders ok in Github, just not the project-awesome.org domain.

**Comment by Dvergar** [comment]
I actually started refactoring it a while ago (by removing the tables altogether) because it did not pass the awesome linter and lost the branch somewhere on a computer.

I did not know, though, that it was not rendered well on this page.

Thanks for letting me know, will fix this 👍.

**Comment by Dvergar** [comment]
Fixed in https://github.com/Dvergar/awesome-haxe-gamedev/commit/a8deb603810f228177944426b6280918f808e010

(I put the images as absolute paths but i'm pretty sure it's gonna be cross-origin blocked)
Edit: It works.
